# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EnglishReader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "EpubExtractor"
  # Pods for EnglishReader

  target 'EnglishReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnglishReaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
